### ISSUE TITLE
Stuff <3

### ISSUE THREAD

**Issue by VanCock** [Truly-Modular/Armory#1]
So first of all I wanted to say that I love your mod, really good stuff, basically Tinker's Construct without all the complicated stuff (it got even worse in 3.0), my main complain is that mod's progression goes only up to getting the modular workbench, no smeltery, no further progression, no nothing, it would be nice if modular workbench was a multi block, requiring bit more work, maybe even locking some stuff behind higher tiers, or forcing player to wait for their tool to process determined on how difficult is their tool, kinda like Tetra, but instead of having to find the workbench structure (which is a common complaint that I have seen) you could have it wherever you desire, also something related to armour design, having more options would definitely be nice, yes I know it's early stages of the mod, not only that, but if I want to add something there's separate API allowing this kind of stuff, but it's something that would be nice, more designs would be great, similar to arsenal, but that's just a thought I wanted to share, it's really a minor stuff and regardless of future plans and changes I still find this project extremely cool, I have to say I was bit surprised there's no cactus armour ([it seemed obvious] correct me if I'm wrong), but other than that I love this mod, really great stuff, keep it up pal.
Cheers.

**Comment by Smartin-b** [comment]
Well, thanks for the feedback, this kinda fell under the radar after the release, sorry for the late answer.
Overall, while some sort of progression would be cool, we wont add that nativly to Truly Modular and its 3 current addons.
BUT - we have already system in places for different ways of locking and hiding options inside the gui and there are plans for addons who would focus on progression overall, but those are still a bit away. ( The system in place can detect player inv, surrounding of the workbench or other stuff about the player like advancements).
Yeah, cactus armor sounds really obvious lol, probably gonna add that xD, the armory and archery are fairly bare bones at this stage in the development, but we have some plans to expand them. At the moment the main focus is to fix issues and compatiblity with other mods, so huge content updates might take a bit.
